#!/bin/sh

[ -e /etc/config/network ] && exit 0

touch /etc/config/network

. /lib/functions/uci-defaults.sh
. /lib/ar71xx.sh

ucidef_set_interface_loopback
ucidef_set_interfaces_lan_wan "eth1" "eth0"
uci commit network
exit 0
